version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khapinchhen-container
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - db
    environment:
      APP_URL: https://khapinchhentole.com
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: khapDB
      DB_USERNAME: khapinchhen
      DB_PASSWORD: m@harjan1
    volumes:
      - ./:/var/www

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: khapDB
      MYSQL_ROOT_PASSWORD: m@harjan1
      MYSQL_USER: khapinchhen
      MYSQL_PASSWORD: m@harjan1
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/database:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

