name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: fabre411
      DOCKER_PASSWORD: maharjan1
      DOCKER_IMAGE_NAME: fabre411/khapinchhen
      VERSION: 1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          # Your deployment script here
          echo "Deploying application..."
      
      - name: Set image tag based on branch and version
        id: tag_branch
        run: |
          BRANCH=${GITHUB_REF_NAME}
          echo "Branch name is: ${BRANCH}"
          if [[ "${BRANCH}" == "main" ]]; then
            echo "::set-output name=tag::release-${VERSION}.${GITHUB_RUN_NUMBER}"
            echo "::set-output name=tagf::release-latest"

          else
            echo "::set-output name=tag::dev-${VERSION}.${GITHUB_RUN_NUMBER}"
            echo "::set-output name=tagf::dev-latest"
          fi

      - name: Build and tag Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker tag fabre411/khapinchhen:latest ${DOCKER_IMAGE_NAME}:${{ steps.tag_branch.outputs.tag }}
          docker tag fabre411/khapinchhen:latest ${DOCKER_IMAGE_NAME}:${{ steps.tag_branch.outputs.tagf }}

      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Docker Image
        run: |

          docker push ${DOCKER_IMAGE_NAME}:${{ steps.tag_branch.outputs.tag }}
          docker push ${DOCKER_IMAGE_NAME}:${{ steps.tag_branch.outputs.tagf }}

      - name: Logout from Docker Hub
        run: docker logout
